### ISSUE TITLE
Timeline for Spring Boot 3.3.x compatible version?

### ISSUE THREAD

**Issue by rsheldon-ansira** [awspring/spring-cloud-aws#1159]
Question: With Spring Boot 3.3.0 and spring-cloud 2023.0.2 released now , is there a plan/timeline for a compatible version of spring-aws-cloud?

By default, the version checking will not let my app start. However I am able to start my app successfully when setting. 

`spring.cloud.compatibility-verifier.enabled=false`

My app is doing very basic integration, so other modules may have compatibility issues I've not run into.

**Comment by MatejNedic** [comment]
Hey @rsheldon-ansira , we are going to release 3.1.2 first and then we are going to release 3.2.0 which will be spring boot 3.3.x compatible.

**Comment by dominik-kovacs** [comment]
@MatejNedic thanks for the info, what is the ETA here?

**Comment by MatejNedic** [comment]
Hey @dominik-kovacs ,
Have to.align with @maciejwalkowiak and @tomazfernandes .
Issue is we are all really really busy at this time.of year.

Will get back to you once we sync internally and see the scope but hopefully we can start moving.

**Comment by mutyasaisrikar** [comment]
@MatejNedic, we are also waiting for this release :)

Is there a tentative date for this release?

**Comment by MatejNedic** [comment]
Hey @mutyasaisrikar , sadly no and it is vacation time. I will be working today and in following days on certain features and preparing them for release. I can't promise but will target ~2 weeks from now.

**Comment by MrLouzao** [comment]
Hello! Do you have any plans of releasing this soon? Just an update about how is it going, please :)

**Comment by AldinDuraki** [comment]
Can you please have a look at this, this is actually blocking our upgrade to 3.3.x and is also a security concern on our end.

**Comment by robertonav20** [comment]
@AldinDuraki me too! if the new release will spent too much time, i think the solution is direct use of aws sdk

**Comment by AldinDuraki** [comment]
Let's see if this week something happens, otherwise I'm forced to migrate to something more frequently maintained.

**Comment by ascopes** [comment]
Might be worth the owners onboarding new additional maintainers if possible? That'd help clear the backlog of PRs too.

**Comment by MatejNedic** [comment]
Some updates to be transperent with community. 
I have spent most time into building Spring Data DynamoDB and have not got time to focus in Spring Cloud AWS that much. Also, I am without my macbook for 1 more week which makes working on spring cloud aws imposible.

It was vacation time for all of us maintainers and since this is not sponsored project it means we are delegating our free time to work on it.

When we moved repoa it became tied to Maciej. We are looking for ways to add my account as well so we can both help eachother, but there are some issues with it which we are looking into.

I will be giving timeline now since I really want to do a release as well. We will be aiming for 20.09.2024.

Will try to squeze in GraalVm hints for nativr image build. S3 spring config import, sqs features and soem DynamoDb improvements. If you want some more features write here or make PR!

I know it has been long time, sorry for that, but we all had other things happening and couldn't spend our free times as much as we wanted to.

**Comment by MatejNedic** [comment]
Also since I gave it away. I would appreciate a lot if you leave suggestions or how you use DynamoDb currently:

https://github.com/awspring/spring-cloud-aws/discussions/1201

I will be sharing pre release design and simple demo in following months :)

**Comment by MatejNedic** [comment]
Spring Cloud AWS 3.2.0 compatible with 3.2.x and 3.3.x released today.

Check [release notes](https://github.com/awspring/spring-cloud-aws/releases/tag/v3.2.0)

Next should be 3.3.x with features mentioned above, we decided to do 3.2.x first with some features and in 3.3.0 add Graal and s3 config.
