### ISSUE TITLE
How to make listener ignore the `JavaType` header 

### ISSUE THREAD

**Issue by totof3110** [awspring/spring-cloud-aws#1165]
**Type**: Bug

**Component**: SQS

**Describe the bug**
We recently migrated a few services from Spring Boot 2.7 to Spring Boot 3.3. We're running into an issue with a new deserialization feature of Spring Cloud AWS. It seems like producers add a new `JavaType` header to the SQS messages containing the class of the payload. When a consumer reads that message, it tries to get the class from that header in `io.awspring.cloud.sqs.support.converter.AbstractMessagingMessageConverter.defaultHeaderTypeMapping(Message<?>)`. However, in our case the producer and consumer are 2 different services and each has a copy of the payload class with a different name/package (and that cannot be changed), which causes a `ClassNotFoundException`.

Is there a way on the consumer side to turn off that behavior / ignore the header and let it fallback to using the `@Payload` argument of the `@SqsListener`?

**Sample**
N/A

**Comment by tomazfernandes** [comment]
Hey @totof3110, you can suppress sending the header in the `SqsTemplate`:

```java
SqsTemplate template = SqsTemplate.builder()
	.sqsAsyncClient(sqsAsyncClient)
	.configureDefaultConverter(AbstractMessagingMessageConverter::doNotSendPayloadTypeHeader)
	.build();
```

Or you can suppress it in the listener side:

```java
    @Bean
    SqsMessageListenerContainerFactory<Object> defaultSqsListenerContainerFactory(SqsAsyncClient sqsAsyncClient) {
        SqsMessagingMessageConverter messageConverter = new SqsMessagingMessageConverter();
        messageConverter.setPayloadTypeMapper(m -> null);

        return SqsMessageListenerContainerFactory
                .builder()
                .configure(options -> options.messageConverter(messageConverter))
                .sqsAsyncClient(sqsAsyncClient)
                .build();
    }
```

Please let me know if that works for you.

**Comment by totof3110** [comment]
Thanks @tomazfernandes ! We'll try that.

**Comment by totof3110** [comment]
Can confirm this work (we used the listener-side solution). Thanks @tomazfernandes

**Comment by pilak** [comment]
another question why this feature is not by default disabled ?

it is break change and most of users wouldn't have to use it

**Comment by neiljbrown** [comment]
Thanks for reporting this issue, and outlining the two suggested solutions above of either  disabling the setting of the 'JavaType' by the message sender (when using SqsTemplate), or disabling the use of the header by all SqsListener. That was useful. I thought it was worth adding the following points - 

1\) Be aware that if you opt for either of the solutions outlined above (based on declaring your own SqsTemplate or Factory bean) the example bean definitions are just the basic minimum. If you use those as-is you’ll lose some additional features that are provided by the auto-configured versions.  For example, the SqsTemplate bean will revert to using a vanilla configured Jackson ObjectMapper instance created by the framework rather than your existing ObjectMapper bean (e.g. the one provided by Boot, which is configured to support additional, commonly required Jackson modules). So if you take this route, see the auto-configured bean definitions in the SQS module's SqsAutoConfiguration class for additional code you may want to add to your bean definitions.

2\) Alternatively, another way of implementing either of the two solutions (on the sender or the listener side) is to declare your own `MessagingMessageConverter` bean instead. This will be used by both the auto-configured SqsTemplate and SqsMessageListenerContainerFactory beans, avoiding the need to replace them and their additionally settings. For example, to implement the solution of disabling use of the JavaType header for all SqsListener - 

```
@Bean
MessagingMessageConverter<Message> messageConverter() {
  SqsMessagingMessageConverter messageConverter =  new SqsMessagingMessageConverter();
  messageConverter.setPayloadTypeMapper(message -> null);
  return messageConverter;
}
```

As per the original code example above, using a payload type mapper which always returns null as above will disable all support for dynamically deriving the target class to which the payload should be deserialised (including the default use of the 'JavaType' SQS message header if present), and instead result in message payloads always being deserialised to the statically defined class of the SqsListener method's payload argument.

Cheers, Neil.
