### ISSUE TITLE
jdk.internal.misc.Unsafe.park(Native Method)

### ISSUE THREAD

**Issue by youcangetme** [awspring/spring-cloud-aws#135]
**Type**: Bug

**Component**:
cloudwatch-metrics-publisher

**Describe the bug**
Shutting down the app results in a "unsafe park" error. Not sure if this is my fault or something new. Just upgrading to 2.3.0

**Sample**
2021-05-12 23:45:37.337 WARN o.a.c.loader.WebappClassLoaderBase   The web application [ROOT] appears to have started a thread named [cloudwatch-metrics-publisher] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.base@15/jdk.internal.misc.Unsafe.park(Native Method)
 java.base@15/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
 java.base@15/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1661)
 java.base@15/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
 java.base@15/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
 java.base@15/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1056)
 java.base@15/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1116)
 java.base@15/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
 java.base@15/java.lang.Thread.run(Thread.java:832)

**JVM**
openjdk version "17-ea" 2021-09-14
OpenJDK Runtime Environment (build 17-ea+5-266)
OpenJDK 64-Bit Server VM (build 17-ea+5-266, mixed mode, sharing)

**Comment by maciejwalkowiak** [comment]
Memory leak like this will take an effect only during WAR deployment, since the application server process lives longer than the application itself. With JAR deployments, this is a non-issue.

@youcangetme there is no `cloudwatch-metrics-publisher` component in Spring Cloud AWS - we only provide auto-configuration for `micrometer-registry-cloudwatch`. Perhaps you can create an issue in https://github.com/micrometer-metrics/micrometer.
