### ISSUE TITLE
how to disable secrets manager config from loading default profile secret, when running with a specific profile

### ISSUE THREAD

**Issue by aspiejane** [awspring/spring-cloud-aws#179]
**Question**

When running springboot with a specific profile **dev**  with secrets manager
    ```
    mvn spring-boot:run -Dspring-boot.run.profiles=dev
    ```
    

aws secrets manager config is loading secrets from both the dev profile `/secret/aws-secrets-dev` and the secret from default profile `/secret/aws-secrets`

```
[main] s.AwsSecretsManagerPropertySourceLocator : Loading secrets from AWS Secret Manager secret with name: /secret/aws-secrets_dev, optional: false
[main] s.AwsSecretsManagerPropertySourceLocator : Loading secrets from AWS Secret Manager secret with name: /secret/aws-secrets, optional: false

```

### How can I prevent secrets manager config from loading `/secret/aws-secrets`?

---

**spring boot 2.5.4** with:

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-bootstrap</artifactId>
    <version>3.0.3</version>
</dependency>

<dependency>
    <groupId>io.awspring.cloud</groupId>
    <artifactId>spring-cloud-starter-aws-secrets-manager-config</artifactId>
    <version>2.3.1</version>
</dependency>
```

**bootstrap.properties**
```
aws.secretsmanager.enabled=false
```

**bootstrap-dev.properties**
```
aws.secretsmanager.name=aws-secrets
aws.secretsmanager.defaultContext=aws-secrets
aws.secretsmanager.enabled=true
```

**Comment by MatejNedic** [comment]
Hey @aspiejane ,
currently there is no way to disable prefix/defaultContext look up. 
If you take a look [here](https://github.com/awspring/spring-cloud-aws/blob/2b58c4513a1a76a83c5c13e91833dd936eae2e0f/spring-cloud-aws-secrets-manager-config/src/main/java/io/awspring/cloud/secretsmanager/AwsSecretsManagerPropertySources.java#L50) you will see that context of loading is always added.

You can check docs as well to have more clear way what is being loaded and in what order.
https://docs.awspring.io/spring-cloud-aws/docs/2.3.1/reference/html/index.html#integrating-your-spring-cloud-application-with-the-aws-secrets-manager
My recommendation is to switch to `spring.config.import` since that will be the way we are going to take Secrets Manager importing. Big difference is that, it gives users a lot more control of which secrets they want to import since you can specify each secret. `spring.config.impor`t can be found explained in docs or you can check the project sample:
[here](https://github.com/awspring/spring-cloud-aws/tree/2.3.x/spring-cloud-aws-samples/spring-cloud-aws-secrets-manager-sample/src/main)

**Comment by aspiejane** [comment]
Thank you
