### ISSUE TITLE
Planned Releases and Community Communication

### ISSUE THREAD

**Issue by kschlesselmann** [awspring/spring-cloud-aws#19]
Hi!

I tried reaching out in gitter but it seems that no one looks at https://gitter.im/spring-cloud/spring-cloud-aws any more.

Where do you plan to communicate planned release dates? We'd like to upgrade to SC 2020.0.0 but it seems there's no compatible SC AWS release yet.

**Comment by MatejNedic** [comment]
Hey @kschlesselmann ,

do you mind opening  [opening discussion](https://github.com/awspring/spring-cloud-aws/discussions) with category `Q&A` please?
I believe it's more clear and better way to communicate then gitter since questions can be searched for.
If you have any more questions or ideas please don't hesitate to open discussion! :)

**Comment by kschlesselmann** [comment]
Yeah, good idea. Didn't know about "Discussions" yet :-)

https://github.com/awspring/spring-cloud-aws/discussions/22
