### ISSUE TITLE
Auto-configure S3 `TransferManager`

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#300]
Transfer Manager for SDK v2 is available in preview. We should add auto-configuration entry for it, that will be triggered only if TransferManager is in the classpath. Docs should include note that TransferManager is in preview.

Additionally, transfer manager compatible `S3OutputStream` implementation including `S3OutputStreamProvider` should be added. 

https://aws.amazon.com/blogs/developer/introducing-amazon-s3-transfer-manager-in-the-aws-sdk-for-java-2-x/

**Comment by krimsz** [comment]
Hey @maciejwalkowiak I think I can help on this one, already did some development on my side to test the waters and it does not seem very complex.  
I do have a question, for the S3OutputStream implementation it looks like we need 99% of the code since we also would need to create a temporary file on disk, if this is the case, is it ok if I change the existing code a bit? This would be to prevent too much code duplication between the existing and the new classes

**Comment by maciejwalkowiak** [comment]
@krimsz yes, definitely it makes sense to not duplicate this piece of code.
