### ISSUE TITLE
Micrometer Observations integration for SQS/SNS by default

### ISSUE THREAD

**Issue by sondemar** [awspring/spring-cloud-aws#566]
**Type**: Feature

**Is your feature request related to a problem? Please describe.**
With a new version of Spring Boot 3.x tracing propagation by Sleuth integration is replaced with Micrometer integration and with the newest version Spring Cloud Sleuth does not support AWS (SQS) integration [anymore](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1876). 

**Describe the solution you'd like**
Integrate Spring Cloud AWS with Micrometer tracing so that tracing propagation works by default for SQS/SNS integration. The tracing SQS message headers get extracted from the message and a trace gets put into the context or tracing context is put into tracing headers for pushed SNS message by default

**Describe alternatives you've considered**
As an alternative it could be porting the [functionality](https://github.com/spring-cloud/spring-cloud-sleuth/pull/1218) from the Spring Cloud Sleuth project.

**Additional context**
Please let me know if you need a contribution to the implementation.

**Comment by tomazfernandes** [comment]
Hi @sondemar, thanks for bringing this up.

We haven't really started looking into `Micrometer` integration, but it's definitely something worth having.

The main challenge I see for this is that the `3.0.0` version code has been completely rewritten, and it's now all async using `CompletableFuture` instances.

I'm not sure how Micrometer works, but if it relies on a similar mechanism as Log4J's `MDC`, with `ThreadLocals`, this might not be so simple due to the multithreaded nature of the solution.

What do you think?

Thanks

**Comment by maciejwalkowiak** [comment]
I think it should be possible as the Micrometer Tracing works also with reactive APIs.

**Comment by sondemar** [comment]
Hi @tomazfernandes. following the comment http://disq.us/p/2rko9pj from @marcingrzejszczak and documentation about ctx propagation https://micrometer.io/docs/contextPropagation what I understand is it will not work out of the box and there should be created a custom "context" mechanism to manage ContextSnapshot to interact with Thread values.

**Comment by maciejwalkowiak** [comment]
Closed in favor of #646
