### ISSUE TITLE
Migrate Secrets Manager integration to AWS SDK 2

### ISSUE THREAD

**Issue by MatejNedic** [awspring/spring-cloud-aws#58]
Secrets Manager integration should be moved from AWS SDK v1 to AWS SDK v2 in 3.0.x branch.

Note: we only need to keep loading properties via `spring.config.import`. Legacy way of importing properties should be removed.

Consider the following guidelines:

* Create package `io.awspring.cloud.autoconfigure.secretsmanager` at `spring-cloud-autoconfigure` which contains `SecretsManagerProperties`, `SecretsManagerBootstrapConfiguration`, `SecretsManagerConfigDataLoader`, `SecretsManagerConfigDataLocationResolver`, `SecretsManagerConfigDataResource`
* Create module `spring-cloud-aws-secrets-manager` which contains `SecretsManagerPropertySource`, `SecretsManagerPropertySourceLocator`, `SecretsManagerPropertySources`
* Create module `spring-cloud-starter-aws-secrets-manager` which contains a `pom.xml` with `spring-cloud-autoconfigure` and `spring-cloud-aws-secrets-manager` dependencies
* Prefix should be `spring.cloud.aws.secretsmanager`

**Comment by arunkpatra** [comment]
@maciejwalkowiak Want me to take this up?

**Comment by MatejNedic** [comment]
@arunkpatra I have already started working on it and I have few small things left to finish, but let's do it like this. Please rebase  [this](https://github.com/awspring/spring-cloud-aws/pull/56) to your branch and use it as a start point for migrating Secrets Manager to AWS SDK 2. If you need help with an issue please message me on Twitter and I will be more than happy to help you out! :)

**Comment by arunkpatra** [comment]
Thanks @MatejNedic. Working on this...

**Comment by kabroadb** [comment]
Does this include updating the paramstore integration as well, or will there be a separate issue for that? I'd be interested in working on that.

**Comment by arunkpatra** [comment]
@kabroadb At the moment I have started on the secrets manager on top of what @maciejwalkowiak has done in #56 which is the foundational PR on V3. Please feel free to contribute, but I would say let me at least from the secretsmanager to a stable state with the tests. Would that be ok?

**Comment by eddumelendez** [comment]
Description updated with guidelines to build the module

**Comment by arunkpatra** [comment]
> Note: we only need to keep loading properties via `spring.config.import`. Legacy way of importing properties should be removed.
> 
> Consider the following guidelines:
> 
> * Create package `io.awspring.cloud.autoconfigure.secretsmanager` at `spring-cloud-autoconfigure` which contains `SecretsManagerProperties`, `SecretsManagerBootstrapConfiguration`, `SecretsManagerConfigDataLoader`, `SecretsManagerConfigDataLocationResolver`, `SecretsManagerConfigDataResource`
> * Create module `spring-cloud-aws-secrets-manager` which contains `SecretsManagerPropertySource`, `SecretsManagerPropertySourceLocator`, `SecretsManagerPropertySources`
> * Create module `spring-cloud-starter-aws-secrets-manager` which contains a `pom.xml` with `spring-cloud-autoconfigure` and `spring-cloud-aws-secrets-manager` dependencies
> * Prefix should be `spring.cloud.aws.secretsmanager`

Thanks for updating the description @eddumelendez, it helps.

- IMO `SecretsManagerBootstrapConfiguration` may not be needed since the `SecretsManagerClient` beans already getting registered by the `AwsSecretsManagerConfigDataLocationResolver`. The other bean `AwsSecretsManagerPropertySourceLocator` which the `AwsSecretsManagerBootstrapConfiguration` was configuring is probably not needed since we are doing away with the legacy style configuration.
- `SecretsManagerPropertySourceLocator` may not be needed since it's only needed by legacy style configuration.
- `SecretsManagerPropertySources` uses `SecretsManagerProperties` which is in `spring-cloud-autoconfigure` module. Hence due to the agreed upon dependency graph, I had to keep `SecretsManagerPropertySources` in `spring-cloud-autoconfigure` module itself.
- Agree on all other points, will rename classes as suggested.

**Comment by eddumelendez** [comment]
Closing in favor of #79
