### ISSUE TITLE
SQS enabled not recognized as a property

### ISSUE THREAD

**Issue by fireXtract** [awspring/spring-cloud-aws#618]
**Type**: Bug

**Component**:
"Secrets Manager", "SQS"

**Describe the bug**
Without any addition configuration, starting the app will give 
`org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.xxx.xxx.inboundmeasurementsapi.InboundMeasurementsApiApplication]: class path resource [io/awspring/cloud/sqs/config/SqsBootstrapConfiguration.class] cannot be opened because it does not exist` when importing starter secrets manager.

Imports
``` xml
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.1</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
...
    <properties>
        <java.version>17</java.version>
        <aws.sdk.version>2.17.280</aws.sdk.version>
        <spring.cloud.version>3.0.0-M3</spring.cloud.version>
    </properties>
...
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>${aws.sdk.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.awspring.cloud</groupId>
                <artifactId>spring-cloud-aws-dependencies</artifactId>
                <version>${spring.cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
...
        <dependency>
            <groupId>io.awspring.cloud</groupId>
            <artifactId>spring-cloud-aws-starter-secrets-manager</artifactId>
        </dependency>
```

**Sample**

Disabling sqs works, but the spring annotation configuration doesn't recognize enabled as a valid property for sqs, but it will for sns and others.
Perhaps the issue is that these are enabled by default even though I've only imported `spring-cloud-aws-starter-secrets-manager`

The workaround is to use the enabled flag anyway.
``` yaml
spring:
  cloud:
    aws:
      sqs:
        enabled: false
```

Without `enabled: false` it will attempt to autoconfigure the sqs despite not importing the cloud-aws modules for sqs

**Comment by tomazfernandes** [comment]
Hi @fireXtract, thanks for bringing this up.

Yeah, I think the problem is that we depend only on `@ConditionalOnClass(SqsAsyncClient.class)` to trigger autoconfiguration, and since the SDK contains that class it must be triggering it erroneously.

We should make it also conditional on a project's class such as `SqsTemplate` so that it doesn't trigger autoconfiguration when the SQS module is not used.

As for why the `sqs.enabled` configuration property is not showing as valid I'm not sure, but I can take a look too.

I should look into this later this week or early next.

Thanks again, and if you have anything else to add feel free to.
