### ISSUE TITLE
Build is failing with Java 11.

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#67]
Running build with Java 11 is failing (probably just an issue with tests).

**Comment by sivaprasadreddy** [comment]
@maciejwalkowiak The tests in `ContextCredentialsConfigurationRegistrarTest` are failing while asserting the following:

```
List<CredentialsProvider> credentialsProviders = (List<CredentialsProvider>) ReflectionTestUtils
				.getField(awsCredentialsProvider, "credentialsProviders");
assertThat(credentialsProviders).hasSize(1);
assertThat(credentialsProviders.get(0)).isInstanceOf(AWSStaticCredentialsProvider.class); //FAILING
```
Here the imported `CredentialsProvider` is `org.apache.http.client.CredentialsProvider`. I think it should be cast to `List<com.amazonaws.auth.AWSCredentialsProvider>` instead of `List<org.apache.http.client.CredentialsProvider>` as follows: 

```
List<AWSCredentialsProvider> credentialsProviders = (List<AWSCredentialsProvider>) ReflectionTestUtils
				.getField(awsCredentialsProvider, "credentialsProviders");
assertThat(credentialsProviders).hasSize(1);
assertThat(credentialsProviders.get(0)).isInstanceOf(AWSStaticCredentialsProvider.class);
```

Casting to `List<org.apache.http.client.CredentialsProvider>` is also done in `io.awspring.cloud.context.config.xml.ContextCredentialsBeanDefinitionParserTest` and `io.awspring.cloud.context.config.annotation.ContextCredentialsConfigurationRegistrarTest` but these tests are passing because there are no `instanceOf()` assert.

I believe casting to `List<com.amazonaws.auth.AWSCredentialsProvider>` instead of `List<org.apache.http.client.CredentialsProvider>`  is the right fix because I don't see `org.apache.http.client.CredentialsProvider` being used in any of the CredentialProvider implementations.

Another way to fix this is to change the way we assert to the following:

From:
```
assertThat(credentialsProviders.get(0)).isInstanceOf(AWSStaticCredentialsProvider.class);
```

To:
```
assertThat(AWSStaticCredentialsProvider.class.isInstance(credentialsProviders.get(0))).isTrue();
```

Still, I am not sure why it is passing in Java 8 but failing in Java 11.

Please let me know your thoughts on this, I can create a PR.
