### ISSUE TITLE
Add User's MappingJackson2MessageConverter to SQS Autoconfiguration

### ISSUE THREAD

**Issue by tomazfernandes** [awspring/spring-cloud-aws#721]
See https://github.com/awspring/spring-cloud-aws/discussions/697#discussion-4918034

**Comment by tomwetjens** [comment]
It seems indeed that a global ObjectMapper bean is picked up for SqsTemplate, but not for SqsListeners.

As a workaround we have now added a customized SqsMessageListenerContainerFactory bean to set the messageConverter explicitly. But it would be great if this will be fixed.

**Comment by tomazfernandes** [comment]
Hi @tomwetjens, would you like to contribute a PR with this logic?

**Comment by berrueta** [comment]
I also ran into this problem. The `ObjectMapper` bean from the context is not automatically picked up for SqsListeners. This seems to be a bug, since [the documentation](https://docs.awspring.io/spring-cloud-aws/docs/3.0.0/reference/html/index.html#message-conversion-and-payload-deserialization) sets the expectation that the `ObjectMapper` should be picked up.

For Kotlin applications, this means that the `ObjectMapper` managed by Spring Boot, which has the Kotlin module (among others), is not automatically wired. Therefore Kotlin data classes cannot be deserialised unless they are explicitly annotated with `@JsonProperty` to make them compatible with the vanilla `ObjectMapper` (without modules) that is instantiated by default by the constructor of `MappingJackson2MessageConverter`.

I've written a [demo application in Kotlin](https://github.com/berrueta/spring-cloud-aws-demo-kotlin) with an integration test that demonstrates the problem. The `MessageListenerTest` fails with "MismatchedInputException: Cannot construct instance of `com.example.demo.Message`".

Adding the `@JsonProperty` annotation makes the test pass:

```kotlin
data class Message(@JsonProperty("payload") val payload: String)
```

**Comment by berrueta** [comment]
Hey @swagregorio , I believe there is already a PR ( #845 ) which should solve this problem.

**Comment by tomazfernandes** [comment]
@swagregorio, the approach you mention is correct.

The aforementioned PR needs some cleaning up but should be merged soon.

In the meantime the provided workaround should work.

**Comment by neiljbrown** [comment]
I’ve just run into this problem as well. In my case I have an @SqsListener method that  requires the SQS message payload to be deserialised to a DTO that includes a field of type java.time.Instant. The deserialisation and hence receipt of the SQS message fails due to the problem this issue addresses - namely that the auto-configured default SQS message listener container factory creates a container using its own vanilla Jackson ObjectMapper instance which isn’t configured with the necessary Jackson modules required to support (de)serialisation of these and other types of fields. 

I noted the workaround suggested above of declaring your own message listener container factory bean to replace the auto-configured one. I additionally wanted to retain support for configuring the container options using the Spring Cloud AWS application config properties (spring.cloud.aws.sqs.listener.*), without maintaining the additional supporting code in my @Configuration class. I’ve therefore implemented an alternative workaround based on using a custom BeanPostProcessor to reconfigure the default container factory instead. I’ve attached a copy of the code below in case it’s of use to any one else between now and when this issue is fixed, released and adopted. 

```
@Component
public class DefaultSqsMessageListenerContainerFactoryBeanPostProcessor implements BeanPostProcessor {
  private static final String DEFAULT_SQS_MLC_FACTORY_BEAN_NAME = "defaultSqsListenerContainerFactory";
  private final ObjectFactory<ObjectMapper> objectMapperBeanFactory;

  public DefaultSqsMessageListenerContainerFactoryBeanPostProcessor(ObjectFactory<ObjectMapper> objectMapperBeanFactory) {
    this.objectMapperBeanFactory = objectMapperBeanFactory;
  }

  @Override
  public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
    if (bean instanceof SqsMessageListenerContainerFactory<?> containerFactory &&
        DEFAULT_SQS_MLC_FACTORY_BEAN_NAME.equals(beanName)) {
      this.configureMessageListenerContainerFactory(containerFactory);
    }
    return bean;
  }

  private void configureMessageListenerContainerFactory(SqsMessageListenerContainerFactory<?> containerFactory) {
    containerFactory.configure(this::updateSqsContainerOptions);
  }

  private void updateSqsContainerOptions(SqsContainerOptionsBuilder optionsBuilder) {
    var converter = new SqsMessagingMessageConverter();
    converter.setObjectMapper(this.objectMapperBeanFactory.getObject());
    optionsBuilder.messageConverter(converter);
  }
}
```

Cheers, Neil.

**Comment by tomazfernandes** [comment]
Completed on https://github.com/awspring/spring-cloud-aws/pull/906
