### ISSUE TITLE
Add option to set DynamoDB table prefix

### ISSUE THREAD

**Issue by maciejwalkowiak** [awspring/spring-cloud-aws#725]
Since all DynamoDB tables live in a single namespace, there should be an option to set a prefix to tables.

For example, currently `DefaultDynamoDbTableNameResolver` for an entity with name `ConfirmedOrder` resolves table name `confirmed_order`. If there are more applications having an entity with the same name, they would use the same table by default.

We should add an option for `DefaultDynamoDbTableNameResolver` to accept a prefix through a property `spring.cloud.aws.dynamodb.table-prefix`, once set, prefix should be added to resolved table name.

If the prefix is not set but the `spring.application.name` is set, it should take a value from `spring.application.name`, append underscore `_` and use it as a prefix.

**Comment by arunkpatra** [comment]
@maciejwalkowiak Can I pick this up?

**Comment by maciejwalkowiak** [comment]
@arunkpatra it's yours 😁

**Comment by arunkpatra** [comment]
@maciejwalkowiak Here are some of my thoughts:

1. It might so happen, that a user has an existing DynamoDB table - `Person` (maybe  this table is shared by a set of apps). They now want to use spring-cloud-aws in a brand new Spring Boot app.
2. Let's say they also want to have `spring.application.name` configured in their new Spring Boot app.
3. If we go fall back to `spring.application.name` as the source of the tablePrefix, then the user is constrained - they would have to rename their table to include the prefix, which they may not be in a position to do so. 
4. Again let's say they need to have the `spring.application.name` also for other purposes e.g. for using Config Server etc.

So IMO, for full backward compatibility for such edge cases, we could do choose one of the two options below:

1. Just have the `tablePrefix` in `DynamoDbProperties` and do not fall back to `spring.application.name`, essentially making `tablePrefix` as a pure opt-in  feature.
2. Have the `tablePrefix`  in `DynamoDbProperties` and fall back to `spring.application.name`. To cover edge cases as I described earlier, we provide an opt-out property named `disableTablePrefix` in `DynamoDbProperties` which will then not source the `tablePrefix` from `spring.application.name`.

I'm leaning towards option  1, since it appears cleaner and simpler. What do you think?

**Comment by maciejwalkowiak** [comment]
Option 1 sounds reasonable. Thanks for the analysis!

**Comment by foogaro** [comment]
@maciejwalkowiak having a single namespace for tables, sounds like a security issue, "hackable" at application level by playing with whose properties.
Isn't there any real multi-tenancy that provides segregation and isolation?

**Comment by maciejwalkowiak** [comment]
Well, you resolve security issues on the IAM level. Anyways, it's AWS design decision not mine 😅

> In an AWS account, table names must be unique within each Region

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html
